### ISSUE TITLE
Unable to run chrome on Windows 8 (6.2.9200)

### ISSUE THREAD

**Issue by fhoshino** [typcn/CrGuard#1]
After applying debug patch, chrome refuse to run in Windows 8 (6.2.9200) x64.

**Comment by typcn** [comment]
Can you attach a screenshot?
or if you have visual studio, please use debug build(dll and exe) it will log some debug information
I only tested it on windows 10

**Comment by fhoshino** [comment]
![tvnviewer_2018-09-28_14-38-50](https://user-images.githubusercontent.com/771955/46192058-72fd9980-c32c-11e8-95b5-5a21914ec39f.png)
Got this error

**Comment by typcn** [comment]
Do you use 32bit version of chrome? You may need the 32bit version.
Also please don't move the exe and dll file after install.

**Comment by fhoshino** [comment]
OS, chrome and CrGuard are all x64

**Comment by typcn** [comment]
Please try to uninstall crguard, and drag chrome.exe on crguard.exe. If
this work, maybe the path in the "Debugger" registry key is incorrect, you
can try to fill it manually

**Comment by fhoshino** [comment]
Chrome runs when dragging to CrGuard.
I guess the culprit is the path with my username contain space.

**Comment by typcn** [comment]
Oh, maybe I forget to add double quotes to the registry value

**Comment by typcn** [comment]
Fixed in https://github.com/typcn/CrGuard/commit/99d18face331632d65cdc3080b6711837e2b490f
