### ISSUE TITLE
Chrome cant boot after installing it

### ISSUE THREAD

**Issue by Luupw3d** [typcn/CrGuard#3]
Chrome cant load any website and keep an white screen.
Try to fix this issue plz.

**Comment by typcn** [comment]
is the chrome just finished updating? just quit chrome and restart it

**Comment by Luupw3d** [comment]
No,it have been updated a few days ago.
Btw,I installed the GreenChrome for my Chrome,maybe it’s caused by it?Have you revived the same feedback?
Thanks!

**Comment by typcn** [comment]
the exe only accepts chrome.exe as process name, can you confirm your exe name?

if this not work do you have visual studio? you can try to compile a debug verson and it will output some log.

CrGuard will only injecte to chrome process with flag: --type=watcher or --type=crashpad-handler

**Comment by Luupw3d** [comment]
![image](https://user-images.githubusercontent.com/23554202/47266735-3c065680-d56d-11e8-95eb-2f06f951f451.png)
![image](https://user-images.githubusercontent.com/23554202/47266738-4294ce00-d56d-11e8-9a33-879f7349960d.png)
![image](https://user-images.githubusercontent.com/23554202/47266740-4a547280-d56d-11e8-979b-1d1eba95a1f3.png)
![image](https://user-images.githubusercontent.com/23554202/47266741-504a5380-d56d-11e8-8616-5c0fa411fd23.png)
![image](https://user-images.githubusercontent.com/23554202/47266753-8091f200-d56d-11e8-878f-03bc694399a9.png)

**Comment by typcn** [comment]
So I think there are more rules needed to add on CreateProcess Hook:

-type=fallback-handler
--no-sandbox

**Comment by typcn** [comment]
should be fixed in https://github.com/typcn/CrGuard/releases/tag/1.4
